/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PasswordDetail: typeof import('./src/components/PasswordDetail.vue')['default']
    PasswordList: typeof import('./src/components/PasswordList.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
